import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import SideBar from "@/ui/SideBar";
import Header from "@/ui/Header";
import Layout from "@/ui/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex">
          <SideBar />
          <div className=" flex flex-col w-full">
            <Layout>{children}</Layout>
          </div>
        </div>
      </body>
    </html>
  );
}
